services:
  # Backend API Service
  - type: web
    name: gestionT2riv
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      

      # Database
      - key: MONGODB_URI
        value: mongodb+srv://hamza:hamza@cluster0.xofqdwg.mongodb.net/creative-association?appName=Cluster0

      # JWT
      - key: JWT_SECRET
        value: e235de07fd51d92e6cb348b359460a1d2604632467975a14dd3ccb87293529541bcb7725f794a74d7f21bba35bdc8e0e770ee4aae5e03a132a232b0d6919a61d
      - key: JWT_EXPIRE
        value: 7d
      - key: JWT_REFRESH_EXPIRE
        value: 30d

      # Upload Configuration
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: UPLOAD_PATH
        value: ./uploads

      # API Configuration
      - key: API_VERSION
        value: v1
      - key: FRONTEND_URL
        value: https://gestiont2riv-tunisian.onrender.com

      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
  # Frontend Static Site
  - type: web
    name: gestionT2riv-tunisian
    env: static
    rootDir: frontend
    plan: free

    buildCommand: npm install && npm run build
    publishDir: dist

    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://gestionT2riv.onrender.com
    routes:
      # 1️⃣ Servir les fichiers statiques (CSS, JS, images, fonts)
      - type: rewrite
        source: /.*\\.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot|map)$
        destination: /$0

      # 2️⃣ SPA : toutes les autres routes vers index.html
      #    status: 200 important pour éviter les 404 sur refresh
      - type: rewrite
        source: /.*
        destination: /index.html
